api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'api'
urlpatterns = [
    path('', views.new, name='signup_'),
]

lev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ui.urls')),
    path('api/', include('api.urls'))
]

ui/urls.py
from django.urls import path
from . import views
app_name = 'ui'
urlpatterns = [
    path('', views.home_page,  name='home'),
    path('signup/', views.sign_up, name='signup'),
]

api/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=64)

    class Meta:
        db_table = 'users'

ui/models.py
from django.db import models

# Create your models here.

api/views.py
import json
from django.http import JsonResponse
from .models import User


def new(request):
    data = json.loads(request.body.decode("utf-8"))
    username = data['user']
    password = data['pass']
    if not User.objects.filter(username=username):
        User.objects.create(username=username, password=password)
        return JsonResponse({
            'status': 'success',
        })
    else:
        return JsonResponse({
            'status': 'failed',
        })


def login(request):
    data = json.loads(request.body.decode("utf-8"))
    username = data['user']
    password = data['pass']
    if User.objects.filter(username=username, password=password):
        return JsonResponse({
            'status': 'success',
        })
    else:
        return JsonResponse({
            'status': 'failed',
        })

ui/views.py
from django.template.response import TemplateResponse

def home_page(request):
    return TemplateResponse(request, 'about.html')

def sign_up(request):
    return TemplateResponse(request, 'sign_up.html')

templates/about.html
{% extends "base.html" %}
{% block title %}
    Wellcome
{% endblock %}
{% block content %}
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <div class="container">
                <a class="navbar-brand font-weight-bolder" href="#">Lev</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#my-menu"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="my-menu">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown font-weight-bold">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Tham gia
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Đăng nhập</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url "ui:signup" %}">Đăng kí</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
        <div class="accordion mt-5" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingOne">
                    <h2 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne"
                                aria-expanded="true" aria-controls="collapseOne">
                            Collapsible Group Item #1
                        </button>
                    </h2>
                </div>

                <div id="collapseOne" class="collapse" aria-labelledby="headingOne"
                     data-parent="#accordionExample">
                    <div class="card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin
                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes
                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings
                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard
                        of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h2 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Collapsible Group Item #2
                        </button>
                    </h2>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin
                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes
                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings
                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard
                        of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingThree">
                    <h2 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Collapsible Group Item #3
                        </button>
                    </h2>
                </div>
                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <div class="card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin
                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes
                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings
                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard
                        of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE>
<html>
<head>
    <link rel="stylesheet" href="{% static "bootstrap.min.css" %}" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
{% block content %} {% endblock %}

<script src="{% static "jquery-3.4.1.min.js" %}"></script>
<script src="{% static "bootstrap.min.js" %}"></script>
</body>
</html>

templates/sign_in.html
{% extends "base.html" %}
{% block title %}
    Đăng kí
{% endblock %}
{% block content %}
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <div class="container">
                <a class="navbar-brand font-weight-bolder" href="#">Lev</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#my-menu"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="my-menu">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item  font-weight-bold">
                            <a class="nav-link " href="{% url "ui:home" %}">
                                Giới thiệu
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
        <div class="ml-5 mt-5">
            <form id="my-form" style="width: 400px">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" class="form-control" id="username" aria-describedby="emailHelp"
                           placeholder="Nhập tên tài khoản">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Nhập mật khẩu">
                </div>
                <input type="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#my-form').on('submit', function (e) {
                e.preventDefault();
                var username = $('#username').val();
                var password = $('#password').val();
                $.ajax({
                    url: '{% url "api:signup_" %}',
                    type: 'post',
                    contentType: 'application/json',
                    data: JSON.stringify({
                        user: username,
                        pass: password,
                    }),
                    headers: {
                        "X-CSRFToken": $('input[name="csrfmiddlewaretoken"]').val()
                    }
                });
                return false;
            })

        })
    </script>

{% endblock %}

templates/sign_up.html
{% extends "base.html" %}
{% block title %}
    Đăng kí
{% endblock %}
{% block content %}
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <div class="container">
                <a class="navbar-brand font-weight-bolder" href="#">Lev</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#my-menu"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="my-menu">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item  font-weight-bold">
                            <a class="nav-link " href="{% url "ui:home" %}">
                                Giới thiệu
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
        <div class="ml-5 mt-5">
            <form id="my-form" style="width: 400px">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" class="form-control" id="username" aria-describedby="emailHelp"
                           placeholder="Nhập tên tài khoản">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Nhập mật khẩu">
                </div>
                <input type="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#my-form').on('submit', function (e) {
                e.preventDefault();
                var username = $('#username').val();
                var password = $('#password').val();
                $.ajax({
                    url: '{% url "api:signup_" %}',
                    type: 'post',
                    contentType: 'application/json',
                    data: JSON.stringify({
                        user: username,
                        pass: password,
                    }),
                    headers: {
                        "X-CSRFToken": $('input[name="csrfmiddlewaretoken"]').val()
                    }
                });
                return false;
            })

        })
    </script>

{% endblock %}